UI design
spanickroon/Market-Place pull request #2
Opened 2020-08-31 14:08 UTC by spanickroon

2020-09-01 00:13 UTC, spanickroon commented
https://marketplace-service.herokuapp.com/login

2020-09-02 15:59 UTC, gmltA requested changes

2020-09-02 15:59 UTC, gmltA commented on static/js/marketplace/main.js
> +}
`showHidePassword4`
`showHidePassword5`

Сіквелы, якія мы не заслугоўваем!

2020-09-02 15:59 UTC, gmltA commented on templates/authentication/base.html
> +        <label class="label-logo" for="...">PLOTUS STORE</label>
`label` doesn't belong here.

2020-09-02 15:59 UTC, gmltA commented on templates/authentication/login.html
> +        <label class="authentication-label" for="...">Password</label>
`for` attribute is incorrect.

2020-09-02 15:59 UTC, gmltA commented on templates/authentication/login.html
> +<a class="authentication-nav nav-target" data-target="signup"  href="#">
`href` is incorrect.

2020-09-02 15:59 UTC, gmltA commented on templates/marketplace/base.html
> +        <a draggable="false" href="#" class="nav-target" data-target="stocks">
Draggable?

2020-09-02 17:16 UTC, spanickroon commented on static/js/marketplace/main.js
> +}
Поправил

2020-09-02 17:16 UTC, spanickroon commented on templates/authentication/base.html
> +        <label class="label-logo" for="...">PLOTUS STORE</label>
Поправил

2020-09-02 17:16 UTC, spanickroon commented on templates/authentication/login.html
> +        <label class="authentication-label" for="...">Password</label>
Поправил

2020-09-02 17:16 UTC, spanickroon commented on templates/authentication/login.html
> +<a class="authentication-nav nav-target" data-target="signup"  href="#">
Поправил

2020-09-02 17:17 UTC, spanickroon commented on templates/marketplace/base.html
> +        <a draggable="false" href="#" class="nav-target" data-target="stocks">
)

2020-09-03 15:36 UTC, gmltA approved these changes

2020-09-03 16:15 UTC, merged