Front-end basics
spanickroon/Market-Place pull request #3
Opened 2020-09-08 11:50 UTC by spanickroon

Ссылочка: https://marketplace-service.herokuapp.com

Сделал маршрутизацию.
Сделал аутентификацию.

Можете зарегистрироваться или зайти в акк:
qwerty
QQwwqq11

Весь остальной функционал в 5 пр будет.
P.S. менять пароль и логин существующего акка пока тоже нельзя.

2020-09-09 20:02 UTC, gmltA requested changes

2020-09-09 20:02 UTC, gmltA commented on templates/marketplace/profile.html
> -            <label for="...">username</label>
`for` няверны

2020-09-10 10:08 UTC, spanickroon commented on templates/marketplace/profile.html
> -            <label for="...">username</label>
Поправил

2020-09-10 18:05 UTC, gmltA approved these changes

2020-09-10 18:27 UTC, merged